docs:
  input: src/docs
  output: /docs
media:
  input: src/media
  output: /media
content:
  - name: docs
    label: Yazılar
    type: collection
    path: content/post
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
  - name: site
    label: Site Ayarları
    path: /config.yml
    type: file
  - name: readme
    label: README ayarlarım
    path: /README.md
    type: file
  - name: static
    label: Statik Klasörü
    path: /static/admin.html
    type: file
    content:
  - name: page
    label: Sayfa Ayarları
    type: collection
    path: content/page
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }