media:
  input: src/media
  output: /media
content:
  - name: docs
    label: Yazılar
    type: collection
    path: content/post
    filename: "{primary}.md"
    view:
      fields: [ title, order ]
      primary: title
      sort: [ order, title ]
      default:
        sort: order
        order: asc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, options: { maxlength: 180 }}
      - { name: order, label: Order, type: number }
      - { name: body, label: Body, type: rich-text }
      
      - name: faq
        label: FAQ
        type: object
        fields:
          - { name: title, label: Title, type: string }
          - name: entries
            label: Entries
            type: object
            list: true
            fields:
              - { name: question, label: Question, type: string }
              - { name: answer, label: Answer, type: text, options: { rows: 5 } }
      - { name: body, label: Body, type: code, options: { format: html} }
