baseURL: "https://basaransemih.github.io"
title: "basaransemih"
DefaultContentLanguage: tr
theme: hugo-PaperMod

languages:
  tr:
    languageName: ":tr:"
    weight: 1
    params:
      languageAltTitle: Turkish
      homeInfoParams:
        Title: "basaransemih"
        Content: Burası benim teknoloji çiftliğim.

menu:
  main:
    - identifier: Anasayfa
      name: Anasayfa
      url: /
      weight: 1
    - identifier: Blog
      name: Blog
      url: /post/
      weight: 2
    - identifier: İletişim
      name: İletişim
      url: /page/iletisim/
      weight: 5
    - identifier: Kategoriler
      name: Kategoriler
      url: /tags/
      weight: 3
    - identifier: Arşiv
      name: "Arşiv"
      url: /arsiv/
      weight: 4
    - identifier: Ara
      name: "Ara \U0001f50d"
      url: /search/
      weight: 6

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    title: "basaransemih"
    description: "Açıklama"
    author: Semih
    DateFormat: "2 January, 2006"
    defaultTheme: auto
    rss: true
    ShowFullTextinRSS: true
    comments: true
    fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

    socialIcons:
        - name: github
          url: "https://github.com/basaransemih"
        - name: email
          url: "mailto:oshidev@proton.me"
        - name: rss
          url: "https://basaransemih.github.io/index.xml"
        - name: spotify
          url: "https://spotify.com/basaransemih"
        - name: xda
          url: "https://xdaforums.com/m/basaransemih.12859096"
        - name: gitlab
          url: "https://gitlab.com/basaransemih"
        - name: other
          url: "https://btt.community/u/basaransemih"
        - name: other
          url: "https://www.technopat.net/sosyal/uye/626016.626016/"
        - name: other
          url: "https://techolay.net/sosyal/uye/7046.2046/"


    editPost:
        URL: "https://github.com/basaransemih/basaransemih.github.io/tree/main/content"
        Text: "Düzenle"
        appendFilePath: true
        
    assets:
        disableHLJS: true
        disableFingerprinting: false
        favicon: "basaransemih.github.io/static/favicon.ico"
