baseURL: "https://sxinar.github.io"
title: "Sxinar"
DefaultContentLanguage: tr
theme: hugo-PaperMod

languages:
  tr:
    languageName: ":tr:"
    weight: 1
    params:
      languageAltTitle: Turkish
      homeInfoParams:
        Title: "Sxinar"
        Content: Burası benim teknoloji çiftliğim.

menu:
  main: 
    - identifier: Anasayfa
      name: Anasayfa
      url: /
      weight: 1
    - identifier: Blog
      name: Blog
      url: /post/
      weight: 2
    - identifier: İletişim
      name: İletişim
      url: /page/iletisim/
      weight: 6
    - identifier: Kategoriler
      name: Kategoriler
      url: /tags/
      weight: 3
      -identifier: Admin
      url: https://prose.io/#Sxinar/sxinar.github.io/tree/main/content/post
      weight: 4
    - identifier: Arşiv
      name: "Arşiv"
      url: /arsiv/
      weight: 5
    - identifier: Ara
      name: "Ara \U0001f50d"
      url: /search/
      weight: 7

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    title: "Sxinar"
    description: "Açıklama"
    author: Sxinar
    DateFormat: "2 January, 2006"
    defaultTheme: auto
    rss: true
    ShowFullTextinRSS: true
    comments: true
    fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

    socialIcons:
        - name: github
          url: "https://github.com/Sxinar"
        - name: email
          url: "mailto:me.unreal462@simplelogin.com"
        - name: rss
          url: "https://sxinar.github.io/index.xml"
        - name: gitlab
          url: "https://gitlab.com/Sxinar"

        
    editPost:
        URL: "https://github.com/Sxinar/Sxinar.github.io/tree/main/content"
        Text: "Düzenle"
        appendFilePath: true
      
